SELECT TITLE,
       COUNT(TICKET_TOTAL_VALUE) AS TICKETS_SOLD
FROM MOVIE_TICKET_SALES
GROUP BY TITLE
EMIT CHANGES
LIMIT 3;

CREATE TABLE MOVIE_TICKETS_SOLD AS
    SELECT TITLE,
           AS_VALUE(TITLE) AS MOVIE_TITLE,
           'AA' AS AA,
           latest_by_offset(sale_ts),
           COUNT(TICKET_TOTAL_VALUE) AS TICKETS_SOLD
    FROM MOVIE_TICKET_SALES
    GROUP BY TITLE
    EMIT CHANGES;


-- Variations
SELECT TITLE,
       COUNT(TICKET_TOTAL_VALUE) AS TICKETS_SOLD,
       SUM(TICKET_TOTAL_VALUE) AS TOTAL_VALUE
FROM MOVIE_TICKET_SALES
GROUP BY TITLE
EMIT CHANGES
LIMIT 3;

CREATE TABLE MOVIE_TICKETS_SOLD_AND_VALUE AS
    SELECT TITLE,
       COUNT(TICKET_TOTAL_VALUE) AS TICKETS_SOLD,
       SUM(TICKET_TOTAL_VALUE) AS TOTAL_VALUE
    FROM MOVIE_TICKET_SALES
    GROUP BY TITLE
    EMIT CHANGES;